repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        # No --fix, just check so it doesn't block commits
      - id: ruff-format
        # Just check, don't format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Disabled hooks that modify files to allow commits with unstaged changes
      # - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: check-merge-conflict
